#!/usr/bin/env python3
"""pass04_negative_controls.py — controls for the run #3 crash-class diagnosis.

PHASE_02_RECONSTRUCTED_POC (pass 04).

What must be proven, and what "proven" means here.

IPHONE13_PHYSICAL_RUN_03 ended with the process gone mid-run; the two mechanisms added in
pass 04 exist so that such a termination is DIAGNOSABLE (a journal naming the last checkpoint,
plus a write-ahead report on disk). A mechanism like that is worthless if it cannot fail, so
every control below has two halves:

  * positive: the real mechanism, exercised by a real process that stops without cooperation,
    is diagnosed correctly;
  * negative: the SAME detector, applied to a deliberately broken arrangement, must report the
    wrong outcome (missing journal, misordered artefacts, ...). If the detector still said
    "diagnosed", it would be proving nothing.

The victim is a small program written to a temporary directory at run time and linked against
the project's REAL Diagnostics sources (phase02_progress.c, phase02_log.c). It terminates
itself with SIGKILL — the only signal that cannot be caught, i.e. exactly the class of
termination that leaves no report behind. Nothing in this file touches the app, the suites or
any result; nothing is installed as a signal handler; no crash is faked.
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIAG_INCLUDE = os.path.join(ROOT, "Diagnostics", "include")
CORE_INCLUDE = os.path.join(ROOT, "RuntimeCore", "include")

VICTIM_SOURCE = r"""
/* Generated by tools/pass04_negative_controls.py — a test victim, never part of the app. */
#include "phase02_log.h"
#include "phase02_progress.h"

#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

static void checkpoint(const char *event, int enabled)
{
    if (enabled != 0) {
        phase02_progress_checkpoint(event);
    }
}

int main(int argc, char **argv)
{
    const char *mode = (argc > 1) ? argv[1] : "finished";
    const char *directory = (argc > 2) ? argv[2] : ".";
    char journal[512];
    int journal_enabled;
    phase02_log_t *log;

    if (strcmp(mode, "reader") == 0) {
        /* The project's own reader, applied to a journal: the assertion is that it finds the
         * last checkpoint in the real format and finds nothing in a look-alike file. */
        char last[PHASE02_PROGRESS_EVENT_MAX + 1u];
        if (argc > 3 && phase02_progress_last_event(argv[3], last, sizeof(last)) == 0) {
            printf("READER_LAST=%s\n", last);
        } else {
            printf("READER_LAST=<none>\n");
        }
        return 0;
    }

    journal_enabled = (strcmp(mode, "disabled-journal") != 0);

    if (phase02_progress_join(directory, "victim-journal.txt", journal, sizeof(journal)) != 0) {
        return 3;
    }
    if (journal_enabled != 0) {
        if (phase02_progress_begin(journal) != 0) {
            return 3;
        }
    }
    checkpoint("RUN_SELECTED_ENTER suite=jit", journal_enabled);
    log = phase02_log_new();
    if (log == NULL) {
        return 3;
    }
    phase02_log_init(log, "PHASE_02_RECONSTRUCTED_POC - crash-class control victim");
    phase02_log_line(log, "# suite: jit");
    phase02_log_record(log, "jit.alloc", RT_PASS, "control victim, not a measurement");
    checkpoint("SUITE_ENTER suite=jit", journal_enabled);

    if (strcmp(mode, "late-write-ahead") == 0) {
        /* Broken order: the risky step is taken BEFORE anything is written to disk. */
        checkpoint("JIT_ENTER_WRITTEN_MEMORY_BEGIN", journal_enabled);
        (void)phase02_progress_write_ahead(log, directory);
        raise(SIGKILL);
    }

    (void)phase02_progress_write_ahead(log, (journal_enabled != 0) ? directory : NULL);
    checkpoint("JIT_ENTER_WRITTEN_MEMORY_BEGIN", journal_enabled);

    if (strcmp(mode, "midsuite") == 0) {
        raise(SIGKILL);           /* the run-03 shape: gone without a chance to report */
    }
    phase02_log_record(log, "jit.make_executable", RT_PASS, "control victim, not a measurement");
    checkpoint("SUITE_EXIT suite=jit", journal_enabled);
    (void)phase02_progress_write_ahead(log, (journal_enabled != 0) ? directory : NULL);
    if (journal_enabled != 0) {
        phase02_progress_end();
    }
    phase02_log_free(log);
    return 0;
}
"""


class Detector:
    """Reads the artefacts of a terminated run the way a human would after a physical failure."""

    def __init__(self, directory: str):
        self.directory = directory
        self.journal_path = os.path.join(directory, "victim-journal.txt")
        self.report_path = os.path.join(directory, "phase02-report-ahead.txt")
        self.events: list[str] = []
        if os.path.exists(self.journal_path):
            with open(self.journal_path, "r", encoding="utf-8", errors="replace") as handle:
                for line in handle:
                    match = re.search(r"event=(.*)$", line.strip())
                    if match:
                        self.events.append(match.group(1))

    @property
    def last_event(self) -> str:
        return self.events[-1] if self.events else ""

    def termination_class(self) -> str:
        """The diagnosis a physical run's artefacts would produce."""
        if not self.events:
            return "UNKNOWN_NO_JOURNAL"
        if "JOURNAL_END" in self.events:
            return "COMPLETED"
        if any(event.startswith("SUITE_ENTER") for event in self.events) and not any(
            event.startswith("SUITE_EXIT") for event in self.events
        ):
            return "TERMINATED_BEFORE_SUITE_EXIT"
        return "TERMINATED_IN_PREFIX"

    def risky_step_is_covered(self) -> bool:
        """The risky checkpoint must come AFTER a write-ahead that reported OK."""
        risky = [i for i, e in enumerate(self.events) if e.startswith("JIT_ENTER_WRITTEN_MEMORY_BEGIN")]
        covered = [i for i, e in enumerate(self.events) if e == "WRITE_AHEAD_OK"]
        if not risky:
            return True                      # no risky step taken: nothing to cover
        return bool(covered) and min(covered) < min(risky)

    def report_on_disk(self) -> bool:
        return os.path.exists(self.report_path) and os.path.getsize(self.report_path) > 0


def project_objects() -> list[str]:
    """The project's own Diagnostics/Platform objects, taken from the host build when it
    exists (that is what the battery builds first) and compiled here when it does not."""
    library = os.path.join(ROOT, "build", "host", "libphase02_runtime_core.a")
    if os.path.exists(library):
        return [library]
    platform_source = (
        "darwin_platform.c" if sys.platform == "darwin" else "linux_platform.c"
    )
    return [
        os.path.join(ROOT, "Diagnostics", "src", "phase02_progress.c"),
        os.path.join(ROOT, "Diagnostics", "src", "phase02_log.c"),
        os.path.join(ROOT, "RuntimeCore", "src", platform_source),
    ]


def branch_of(text: str, anchor: str) -> str:
    """Brace-matched extraction of the block that starts at `anchor` ("" when absent)."""
    start = text.find(anchor)
    if start < 0:
        return ""
    depth = 0
    for position in range(start, len(text)):
        if text[position] == "{":
            depth += 1
        elif text[position] == "}":
            depth -= 1
            if depth == 0:
                return text[start:position + 1]
    return ""


def compile_victim(workdir: str) -> str:
    source = os.path.join(workdir, "victim.c")
    binary = os.path.join(workdir, "victim")
    with open(source, "w", encoding="utf-8") as handle:
        handle.write(VICTIM_SOURCE)
    command = [
        "cc", "-std=c11", "-Wall", "-Wextra", "-Werror",
        "-I", DIAG_INCLUDE, "-I", CORE_INCLUDE,
        source,
    ] + project_objects() + [
        "-o", binary,
    ]
    build = subprocess.run(command, capture_output=True, text=True)
    if build.returncode != 0:
        raise RuntimeError(f"could not compile the control victim:\n{build.stderr}")
    return binary


def run_victim(binary: str, mode: str, workdir: str) -> int:
    case = os.path.join(workdir, f"case-{mode}")
    os.makedirs(case, exist_ok=True)
    result = subprocess.run([binary, mode, case], capture_output=True, text=True)
    return result.returncode, case


def main() -> int:
    checks: list[tuple[str, bool, str]] = []

    def check(name: str, ok: bool, detail: str = "") -> None:
        checks.append((name, bool(ok), detail))

    workdir = tempfile.mkdtemp(prefix="phase02-pc04-")
    try:
        binary = compile_victim(workdir)

        # ---- PC1: a hard termination mid-run is diagnosed, and the diagnosis discriminates.
        rc, case = run_victim(binary, "midsuite", workdir)
        detector = Detector(case)
        check("PC1 the victim was killed by SIGKILL (rc=-9)", rc == -9, f"rc={rc}")
        check("PC1 the journal survives the kill and names the last checkpoint",
              detector.last_event == "JIT_ENTER_WRITTEN_MEMORY_BEGIN",
              f"last={detector.last_event!r}")
        check("PC1 the diagnosis names the run-03 class",
              detector.termination_class() == "TERMINATED_BEFORE_SUITE_EXIT",
              detector.termination_class())
        rc, case = run_victim(binary, "disabled-journal", workdir)
        negative = Detector(case)
        check("PC1-N with the recorder disabled the same detector reports UNKNOWN (it is not "
              "always-passing)", negative.termination_class() == "UNKNOWN_NO_JOURNAL",
              negative.termination_class())

        # ---- PC2: a completed run is NOT reported as a termination (the other direction).
        rc, case = run_victim(binary, "finished", workdir)
        detector = Detector(case)
        check("PC2 a completed run exits 0", rc == 0, f"rc={rc}")
        check("PC2 a completed run is diagnosed as COMPLETED",
              detector.termination_class() == "COMPLETED", detector.termination_class())
        check("PC2-N the kill case from PC1 is NOT diagnosed as COMPLETED",
              Detector(os.path.join(workdir, "case-midsuite")).termination_class()
              != "COMPLETED",
              Detector(os.path.join(workdir, "case-midsuite")).termination_class())

        # ---- PC3: the write-ahead report exists on disk before the risky step.
        rc, case = run_victim(binary, "midsuite", workdir)
        detector = Detector(case)
        check("PC3 a report is on disk even though the run was killed",
              detector.report_on_disk(), detector.report_path)
        if detector.report_on_disk():
            with open(detector.report_path, "r", encoding="utf-8", errors="replace") as handle:
                text = handle.read()
            check("PC3 the report on disk contains the measurements taken before the kill",
                  "[PHASE02] TEST=jit.alloc" in text and "# suite: jit" in text,
                  f"{len(text)} bytes")
        check("PC3 the risky step is covered by a write-ahead that reported OK",
              detector.risky_step_is_covered(), ",".join(detector.events))
        rc, case = run_victim(binary, "late-write-ahead", workdir)
        broken = Detector(case)
        check("PC3-N a victim that takes the risky step before writing anything is flagged "
              "as uncovered", not broken.risky_step_is_covered(),
              ",".join(broken.events))

        # ---- PC5: the bridge emits the checkpoint set the next physical run depends on, in
        # order, and nothing inside the suite body (no flooding).
        bridge_path = os.path.join(ROOT, "RuntimePoC", "Phase02Bridge.m")
        with open(bridge_path, "r", encoding="utf-8") as handle:
            bridge = handle.read()

        def checkpoint_order(text: str) -> list[str]:
            return re.findall(r"phase02_progress_checkpoint(?:_kv)?\(\s*\"([A-Z_]+)\"", text)

        order = checkpoint_order(bridge)
        required = ["RUN_SELECTED_ENTER", "HARNESS_INIT_ENTER", "HARNESS_INIT_OK",
                    "SUITE_DISPATCH_ENTER", "SUITE_DISPATCH_END", "RUN_SELECTED_EXIT"]
        positions = [order.index(name) for name in required if name in order]
        check("PC5 the bridge emits the whole checkpoint set", len(positions) == len(required),
              ",".join(order))
        check("PC5 the checkpoints appear in execution order",
              positions == sorted(positions) and len(positions) > 0, ",".join(order))
        check("PC5 the bridge emits no checkpoint inside the suite body",
              order.count("SUITE_FIRST_TEST_ENTER") == 0 and
              len(checkpoint_order(bridge)) == len(order),
              ",".join(order))
        broken_bridge = bridge.replace("phase02_progress_checkpoint(\"HARNESS_INIT_OK\");", "")
        broken_order = checkpoint_order(broken_bridge)
        check("PC5-N dropping one checkpoint is detected by the same check",
              "HARNESS_INIT_OK" not in broken_order, ",".join(broken_order))

        # ---- PC6: the two deferral branches exist, are guarded by the object-view / enter
        # policies, and never execute the thing they defer. The runtime observation of these
        # branches belongs to the device (the journal and the report on it will name them);
        # what a host can and must check is that they say BLOCKED, name the reason, and contain
        # no fallback that would take the risky step anyway.
        with open(os.path.join(ROOT, "Diagnostics", "src", "phase02_harness.c"),
                  "r", encoding="utf-8") as handle:
            harness = handle.read()

        def branch(anchor: str) -> str:
            start = harness.find(anchor)
            if start < 0:
                return ""
            depth = 0
            for position in range(start, len(harness)):
                if harness[position] == "{":
                    depth += 1
                elif harness[position] == "}":
                    depth -= 1
                    if depth == 0:
                        return harness[start:position + 1]
            return ""

        jit_branch = branch('if (phase02_execution_allowed(PHASE02_EXEC_OP_ENTER_WRITTEN_MEMORY) == 0)')
        check("PC6 the JIT chain has a policy-guarded deferral branch", jit_branch != "")
        check("PC6 the JIT deferral reports BLOCKED and names the policy reason",
              "RT_BLOCKED" in jit_branch and "phase02_execution_reason" in jit_branch,
              jit_branch[:120])
        check("PC6 the JIT deferral does not make the arena executable",
              "rt_jit_make_executable" not in jit_branch and "rt_mem_protect" not in jit_branch,
              "no protection change in the deferred branch")
        check("PC6 the JIT deferral does not call the generated code",
              "payload_fn" not in jit_branch and "rt_jit_execute" not in jit_branch,
              "no execution in the deferred branch")
        object_branch = branch("if (phase02_execution_allowed(PHASE02_EXEC_OP_OBJECT_EXEC_VIEW) == 0)")
        check("PC6 the object-view deferral reports BLOCKED with the named path's own stage",
              object_branch != "" and "RT_BLOCKED" in object_branch and
              "named_stage" in object_branch and "memory.dual_mapping_rw_rx" in object_branch,
              object_branch[:120])
        check("PC6 the object-view deferral does not create the executable view",
              "rt_dual_map_create_file_backed" not in object_branch,
              "no executable mapping in the deferred branch")
        loader_start = harness.find("static rt_status_t phase02_suite_loader(")
        loader_body = harness[loader_start:] if loader_start >= 0 else ""
        loader_branch = branch_of(
            loader_body,
            "if (phase02_execution_allowed(PHASE02_EXEC_OP_ENTER_WRITTEN_MEMORY) == 0) {")
        check("PC6 the loader deferral reports BLOCKED and does not enter the entry point",
              loader_branch != "" and "RT_BLOCKED" in loader_branch and
              "image validated and accepted" in loader_branch and
              "phase02_execution_reason" in loader_branch and
              "rt_loader_run_ex" not in loader_branch,
              loader_branch[:120])

        # negative twin: the same checks must fail when the guard is removed from one branch
        broken_harness = harness.replace(
            "if (phase02_execution_allowed(PHASE02_EXEC_OP_OBJECT_EXEC_VIEW) == 0) {",
            "if (1) {", 1)
        broken_object_branch = branch_of(broken_harness,
                                         "if (1) {\n                /* The named path was attempted")
        check("PC6-N a branch whose policy guard was removed is no longer recognisable as guarded",
              "phase02_execution_allowed" not in broken_object_branch,
              broken_object_branch[:80])

        # ---- PC4: the project's own reader reads the project's own journal, and nothing else.
        kill_case = os.path.join(workdir, "case-midsuite")
        real_journal = os.path.join(kill_case, "victim-journal.txt")
        reader = subprocess.run([binary, "reader", kill_case, real_journal],
                                capture_output=True, text=True).stdout.strip()
        check("PC4 the project's reader names the last checkpoint of a killed run",
              reader == "READER_LAST=JIT_ENTER_WRITTEN_MEMORY_BEGIN", reader)
        lookalike = os.path.join(workdir, "lookalike-journal.txt")
        with open(lookalike, "w", encoding="utf-8") as handle:
            handle.write("last event: SUITE_EXIT\n")   # plausible, wrong format
        reader = subprocess.run([binary, "reader", kill_case, lookalike],
                                capture_output=True, text=True).stdout.strip()
        check("PC4-N a look-alike journal cannot fake a last checkpoint",
              reader == "READER_LAST=<none>", reader)
    finally:
        shutil.rmtree(workdir, ignore_errors=True)

    failures = [name for name, ok, _ in checks if not ok]
    for name, ok, detail in checks:
        print(("ok   " if ok else "FAIL ") + name + (f"  [{detail}]" if detail and not ok else ""))
    print(f"PASS04_NEGATIVE_CONTROLS={len(checks) - len(failures)}/{len(checks)}")
    return 0 if not failures else 1


if __name__ == "__main__":
    sys.exit(main())
